[package]
name = "remander"
version = "0.1.0"
authors = ["manderio <git@mander.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust = "4"
cron = "0.9.0"
structopt = "0.3"
